'use strict';
const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  SALES_MANAGER: 'sales_manager',
  WAREHOUSE_MANAGER: 'warehouse_manager',
  CUSTOMER_SUPPORT: 'customer_support',
  CUSTOMER: 'customer',
};
const ROLE_LIST = Object.values(ROLES);

const ROLE_GROUPS = {
  ALL_STAFF: [
    ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SALES_MANAGER,
    ROLES.WAREHOUSE_MANAGER, ROLES.CUSTOMER_SUPPORT,
  ],
  INVENTORY_WRITE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.WAREHOUSE_MANAGER],
  CUSTOMER_WRITE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SALES_MANAGER],
  SALES_WRITE: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.SALES_MANAGER],
  ADMIN_MANAGE: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
};

module.exports = { ROLES, ROLE_LIST, ROLE_GROUPS };
